name: learn-github-actions

run-name: ${{ github.actor }} creating pi-image
on: [push]
jobs:
  check-bats-version:
    # runs-on: ubuntu-latest 
    runs-on: self-hosted
    steps:
    - uses: usimd/pi-gen-action@v1
      with:
        image-name: test
        verbose-output: true
      
